apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../rabbitmq

configMapGenerator:
  - name: scripts
    files:
    - scripts/generate_secrets.sh
    - scripts/generate_ssl_certificates.sh
    - scripts/database_entrypoint.sh
  - name: app-config
    envs:
      - .env.example
