apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ../shared

configMapGenerator:
  - name: app-config
    behavior: merge
    envs:
      - .env.example
