name: Push Docker images to Docker Hub

on:
  push:
  pull_request:
    types:
      - closed
    branches:
      - main
      - dev

# These environment variables are required during runtime but not build time.
# As it is not possible to specify this in Docker compose,
# we pass dummy environment variables in order for this step to succeed.
env:
  SECRETS_DIR: /this/is/a/dummy/path
  SSL_DIR: /this/is/a/dummy/path

jobs:
  build-and-push-head-office:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: omarbesbes/database-synchronization-app:head-office
          build-args: |
            OFFICE_TYPE=head

  build-and-push-branch-office:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: omarbesbes/database-synchronization-app:branch-office
          build-args: |
            OFFICE_TYPE=branch
            
